"""Synthetic data service for the Phase 2A government monitoring dashboard.

The values in this module are deliberately illustrative. They are not real
government observations and the prototype freshness rules are not medical or
epidemiological thresholds.
"""

from copy import deepcopy
from typing import Any


DEMO_VILLAGES: list[dict[str, Any]] = [
    {
        "id": "ASM-CCH-001",
        "name": "Demo Village 01",
        "district": "Cachar",
        "state": "Assam",
        "population": 3250,
        "risk_score": 86,
        "confidence_score": 52,
        "alert_level": "HIGH",
        "rainfall_risk": "HIGH",
        "flood_risk": "HIGH",
        "water_quality_status": "UNKNOWN",
        "health_signal": "MODERATE",
        "water_test_age_days": 92,
        "health_report_age_days": 9,
        "needs_verification": True,
        "data_source": "synthetic",
    },
    {
        "id": "ASM-CCH-002",
        "name": "Demo Village 02",
        "district": "Cachar",
        "state": "Assam",
        "population": 2810,
        "risk_score": 78,
        "confidence_score": 81,
        "alert_level": "HIGH",
        "rainfall_risk": "HIGH",
        "flood_risk": "MODERATE",
        "water_quality_status": "WATCH",
        "health_signal": "ELEVATED",
        "water_test_age_days": 18,
        "health_report_age_days": 4,
        "needs_verification": False,
        "data_source": "synthetic",
    },
    {
        "id": "ASM-HLK-003",
        "name": "Demo Village 03",
        "district": "Hailakandi",
        "state": "Assam",
        "population": 1940,
        "risk_score": 75,
        "confidence_score": 43,
        "alert_level": "HIGH",
        "rainfall_risk": "MODERATE",
        "flood_risk": "HIGH",
        "water_quality_status": "UNKNOWN",
        "health_signal": "UNKNOWN",
        "water_test_age_days": 76,
        "health_report_age_days": None,
        "needs_verification": True,
        "data_source": "synthetic",
    },
    {
        "id": "ASM-HLK-004",
        "name": "Demo Village 04",
        "district": "Hailakandi",
        "state": "Assam",
        "population": 4170,
        "risk_score": 64,
        "confidence_score": 69,
        "alert_level": "PREPAREDNESS",
        "rainfall_risk": "HIGH",
        "flood_risk": "MODERATE",
        "water_quality_status": "WATCH",
        "health_signal": "MODERATE",
        "water_test_age_days": 27,
        "health_report_age_days": 7,
        "needs_verification": False,
        "data_source": "synthetic",
    },
    {
        "id": "ASM-KRG-005",
        "name": "Demo Village 05",
        "district": "Karimganj",
        "state": "Assam",
        "population": 2360,
        "risk_score": 61,
        "confidence_score": 58,
        "alert_level": "PREPAREDNESS",
        "rainfall_risk": "MODERATE",
        "flood_risk": "MODERATE",
        "water_quality_status": "UNKNOWN",
        "health_signal": "LOW",
        "water_test_age_days": 64,
        "health_report_age_days": 12,
        "needs_verification": True,
        "data_source": "synthetic",
    },
    {
        "id": "ASM-KRG-006",
        "name": "Demo Village 06",
        "district": "Karimganj",
        "state": "Assam",
        "population": 3580,
        "risk_score": 57,
        "confidence_score": 74,
        "alert_level": "PREPAREDNESS",
        "rainfall_risk": "MODERATE",
        "flood_risk": "LOW",
        "water_quality_status": "CLEAR",
        "health_signal": "MODERATE",
        "water_test_age_days": 34,
        "health_report_age_days": 6,
        "needs_verification": False,
        "data_source": "synthetic",
    },
    {
        "id": "MNP-IMP-007",
        "name": "Demo Village 07",
        "district": "Imphal East",
        "state": "Manipur",
        "population": 2240,
        "risk_score": 51,
        "confidence_score": 49,
        "alert_level": "PREPAREDNESS",
        "rainfall_risk": "LOW",
        "flood_risk": "MODERATE",
        "water_quality_status": "NOT_REPORTED",
        "health_signal": "UNKNOWN",
        "water_test_age_days": None,
        "health_report_age_days": None,
        "needs_verification": True,
        "data_source": "synthetic",
    },
    {
        "id": "MNP-IMP-008",
        "name": "Demo Village 08",
        "district": "Imphal East",
        "state": "Manipur",
        "population": 3090,
        "risk_score": 39,
        "confidence_score": 88,
        "alert_level": "NORMAL",
        "rainfall_risk": "LOW",
        "flood_risk": "LOW",
        "water_quality_status": "CLEAR",
        "health_signal": "LOW",
        "water_test_age_days": 11,
        "health_report_age_days": 3,
        "needs_verification": False,
        "data_source": "synthetic",
    },
    {
        "id": "MNP-UKL-009",
        "name": "Demo Village 09",
        "district": "Ukhrul",
        "state": "Manipur",
        "population": 1680,
        "risk_score": 37,
        "confidence_score": 46,
        "alert_level": "NORMAL",
        "rainfall_risk": "LOW",
        "flood_risk": "LOW",
        "water_quality_status": "CLEAR",
        "health_signal": "UNKNOWN",
        "water_test_age_days": 22,
        "health_report_age_days": None,
        "needs_verification": True,
        "data_source": "synthetic",
    },
    {
        "id": "MNP-UKL-010",
        "name": "Demo Village 10",
        "district": "Ukhrul",
        "state": "Manipur",
        "population": 2120,
        "risk_score": 34,
        "confidence_score": 80,
        "alert_level": "NORMAL",
        "rainfall_risk": "LOW",
        "flood_risk": "LOW",
        "water_quality_status": "CLEAR",
        "health_signal": "LOW",
        "water_test_age_days": 8,
        "health_report_age_days": 2,
        "needs_verification": False,
        "data_source": "synthetic",
    },
    {
        "id": "MIZ-AIZ-011",
        "name": "Demo Village 11",
        "district": "Aizawl",
        "state": "Mizoram",
        "population": 2760,
        "risk_score": 31,
        "confidence_score": 77,
        "alert_level": "NORMAL",
        "rainfall_risk": "MODERATE",
        "flood_risk": "LOW",
        "water_quality_status": "CLEAR",
        "health_signal": "LOW",
        "water_test_age_days": 71,
        "health_report_age_days": 5,
        "needs_verification": False,
        "data_source": "synthetic",
    },
    {
        "id": "MIZ-AIZ-012",
        "name": "Demo Village 12",
        "district": "Aizawl",
        "state": "Mizoram",
        "population": 1850,
        "risk_score": 28,
        "confidence_score": 83,
        "alert_level": "NORMAL",
        "rainfall_risk": "LOW",
        "flood_risk": "LOW",
        "water_quality_status": "CLEAR",
        "health_signal": "LOW",
        "water_test_age_days": 16,
        "health_report_age_days": 4,
        "needs_verification": False,
        "data_source": "synthetic",
    },
    {
        "id": "TRP-DLI-013",
        "name": "Demo Village 13",
        "district": "Dhalai",
        "state": "Tripura",
        "population": 3410,
        "risk_score": 26,
        "confidence_score": 73,
        "alert_level": "NORMAL",
        "rainfall_risk": "LOW",
        "flood_risk": "LOW",
        "water_quality_status": "CLEAR",
        "health_signal": "LOW",
        "water_test_age_days": 5,
        "health_report_age_days": 3,
        "needs_verification": False,
        "data_source": "synthetic",
    },
    {
        "id": "TRP-DLI-014",
        "name": "Demo Village 14",
        "district": "Dhalai",
        "state": "Tripura",
        "population": 2030,
        "risk_score": 22,
        "confidence_score": 86,
        "alert_level": "NORMAL",
        "rainfall_risk": "LOW",
        "flood_risk": "LOW",
        "water_quality_status": "CLEAR",
        "health_signal": "LOW",
        "water_test_age_days": 29,
        "health_report_age_days": 8,
        "needs_verification": False,
        "data_source": "synthetic",
    },
    {
        "id": "TRP-UNK-015",
        "name": "Demo Village 15",
        "district": "Unakoti",
        "state": "Tripura",
        "population": 2980,
        "risk_score": 18,
        "confidence_score": 79,
        "alert_level": "NORMAL",
        "rainfall_risk": "LOW",
        "flood_risk": "LOW",
        "water_quality_status": "CLEAR",
        "health_signal": "LOW",
        "water_test_age_days": 48,
        "health_report_age_days": 5,
        "needs_verification": False,
        "data_source": "synthetic",
    },
]

DEMO_FORECAST = {
    "weeks": [
        {
            "week": 1,
            "label": "Week 1",
            "risk_level": "NORMAL",
            "drivers": ["Current health signals remain low", "Recent water tests available"],
        },
        {
            "week": 2,
            "label": "Week 2",
            "risk_level": "PREPAREDNESS",
            "drivers": ["Synthetic rainfall signal increasing", "Flood exposure under watch"],
        },
        {
            "week": 3,
            "label": "Week 3",
            "risk_level": "HIGH",
            "drivers": ["Peak demo rainfall signal", "Several water tests may become stale"],
        },
        {
            "week": 4,
            "label": "Week 4",
            "risk_level": "PREPAREDNESS",
            "drivers": ["Flood signal easing", "Field verification remains important"],
        },
    ],
    "explanation": "A synthetic district-level preparedness scenario based on illustrative environmental and reporting signals.",
    "disclaimer": "This is a preparedness outlook, not confirmation that an outbreak will occur.",
    "data_source": "synthetic",
}

DEMO_RAINFALL_DISEASE_TREND = {
    "location_scope": "Synthetic multi-district demonstration",
    "period_unit": "week",
    "rainfall_unit": "millimetres",
    "case_unit": "reported cases",
    "weeks": [
        {"week_start": "2026-05-18", "label": "18 May", "rainfall_mm": 38, "reported_cases": 4},
        {"week_start": "2026-05-25", "label": "25 May", "rainfall_mm": 52, "reported_cases": 5},
        {"week_start": "2026-06-01", "label": "01 Jun", "rainfall_mm": 84, "reported_cases": 6},
        {"week_start": "2026-06-08", "label": "08 Jun", "rainfall_mm": 126, "reported_cases": 8},
        {"week_start": "2026-06-15", "label": "15 Jun", "rainfall_mm": 178, "reported_cases": 10},
        {"week_start": "2026-06-22", "label": "22 Jun", "rainfall_mm": 151, "reported_cases": 15},
        {"week_start": "2026-06-29", "label": "29 Jun", "rainfall_mm": 96, "reported_cases": 19},
        {"week_start": "2026-07-06", "label": "06 Jul", "rainfall_mm": 68, "reported_cases": 17},
        {"week_start": "2026-07-13", "label": "13 Jul", "rainfall_mm": 44, "reported_cases": 12},
        {"week_start": "2026-07-20", "label": "20 Jul", "rainfall_mm": 57, "reported_cases": 9},
    ],
    "explanation": "Synthetic peaks occur at different times to illustrate a pattern that future analysis may test.",
    "disclaimer": "Illustrative association only. This synthetic trend does not establish causation or a medically validated rainfall-to-disease lag.",
    "future_analysis_note": "Future real datasets will be used to estimate rainfall-to-disease lag statistically.",
    "data_source": "synthetic",
}

DEMO_TASKS = [
    {
        "id": "TASK-COMM-001",
        "priority": 1,
        "village_id": "ASM-HLK-004",
        "village_name": "Demo Village 04",
        "district": "Hailakandi",
        "action": "Inspect reported sewage overflow near Community Well W04",
        "reasons": [
            "Multiple citizen reports",
            "Location near a drinking-water source",
            "Currently unverified",
        ],
        "source_type": "COMMUNITY_REPORT",
        "community_report_id": "CR-002",
        "data_source": "synthetic",
    },
    {
        "id": "TASK-001",
        "priority": 2,
        "village_id": "ASM-CCH-001",
        "village_name": "Demo Village 01",
        "district": "Cachar",
        "action": "Test community water source",
        "reasons": ["High modeled risk", "Water data is stale", "Flood signal is elevated"],
        "data_source": "synthetic",
    },
    {
        "id": "TASK-002",
        "priority": 3,
        "village_id": "ASM-HLK-003",
        "village_name": "Demo Village 03",
        "district": "Hailakandi",
        "action": "Request health-worker report",
        "reasons": ["High risk with low confidence", "Health report is missing", "Water data is stale"],
        "data_source": "synthetic",
    },
    {
        "id": "TASK-003",
        "priority": 4,
        "village_id": "ASM-KRG-005",
        "village_name": "Demo Village 05",
        "district": "Karimganj",
        "action": "Inspect chlorination records",
        "reasons": ["Preparedness alert active", "Water test exceeds demo freshness rule"],
        "data_source": "synthetic",
    },
    {
        "id": "TASK-004",
        "priority": 5,
        "village_id": "MNP-IMP-007",
        "village_name": "Demo Village 07",
        "district": "Imphal East",
        "action": "Collect baseline field evidence",
        "reasons": ["Water and health reports are missing", "Assessment confidence is low"],
        "data_source": "synthetic",
    },
    {
        "id": "TASK-005",
        "priority": 6,
        "village_id": "MNP-UKL-009",
        "village_name": "Demo Village 09",
        "district": "Ukhrul",
        "action": "Request health-worker verification",
        "reasons": ["Health report is missing", "Assessment confidence is low"],
        "data_source": "synthetic",
    },
]


def get_villages(
    alert_level: str | None = None,
    district: str | None = None,
    needs_verification: bool | None = None,
) -> list[dict[str, Any]]:
    """Return risk-sorted synthetic village summaries with optional filters."""
    villages = DEMO_VILLAGES
    if alert_level:
        villages = [item for item in villages if item["alert_level"] == alert_level.upper()]
    if district:
        villages = [item for item in villages if item["district"].casefold() == district.casefold()]
    if needs_verification is not None:
        villages = [item for item in villages if item["needs_verification"] is needs_verification]
    return deepcopy(sorted(villages, key=lambda item: item["risk_score"], reverse=True))


def get_village(village_id: str) -> dict[str, Any] | None:
    village = next((item for item in DEMO_VILLAGES if item["id"] == village_id), None)
    return deepcopy(village) if village else None


def get_overview() -> dict[str, int | str]:
    """Build overview counts instead of maintaining duplicate hard-coded totals."""
    return {
        "total_villages": len(DEMO_VILLAGES),
        "normal": sum(item["alert_level"] == "NORMAL" for item in DEMO_VILLAGES),
        "preparedness": sum(item["alert_level"] == "PREPAREDNESS" for item in DEMO_VILLAGES),
        "high_risk": sum(item["alert_level"] == "HIGH" for item in DEMO_VILLAGES),
        "needs_verification": sum(item["needs_verification"] for item in DEMO_VILLAGES),
        "stale_water_tests": sum(
            item["water_test_age_days"] is not None and item["water_test_age_days"] > 60
            for item in DEMO_VILLAGES
        ),
        "data_source": "synthetic",
    }


def get_forecast() -> dict[str, Any]:
    return deepcopy(DEMO_FORECAST)


def get_rainfall_disease_trend() -> dict[str, Any]:
    return deepcopy(DEMO_RAINFALL_DISEASE_TREND)


def get_tasks() -> list[dict[str, Any]]:
    return deepcopy(DEMO_TASKS)
