import { useEffect, useState } from "react";
import Icon from "../components/Icon.jsx";
import RiskBadge from "../components/RiskBadge.jsx";
import { getForecast } from "../services/api.js";

function OutlookPage({ onConnectionChange }) {
  const [state, setState] = useState({ status: "loading", forecast: null, error: "" });
  useEffect(() => { const controller = new AbortController(); getForecast(controller.signal).then((forecast) => { setState({ status: "ready", forecast, error: "" }); onConnectionChange("connected"); }).catch((error) => { if (error.name !== "AbortError") { setState({ status: "error", forecast: null, error: error.message }); onConnectionChange("unavailable"); } }); return () => controller.abort(); }, [onConnectionChange]);
  return <div className="px-5 py-7 lg:px-8 lg:py-8"><p className="text-sm font-semibold text-blue-700">Preparedness planning</p><h1 className="mt-1 text-3xl font-bold tracking-tight">4-Week Outlook</h1><p className="mt-2 text-sm text-slate-500">An illustrative forward view of environmental and evidence-readiness signals.</p>{state.status === "loading" && <div className="mt-6 h-72 animate-pulse rounded-2xl bg-white" role="status"><span className="sr-only">Loading outlook</span></div>}{state.status === "error" && <p className="mt-6 rounded-xl bg-rose-50 p-5 text-rose-800" role="alert">{state.error}</p>}{state.forecast && <><section className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{state.forecast.weeks.map((week, index) => <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm" key={week.week}><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Planning period {index + 1}</p><h2 className="mt-1 text-xl font-bold">{week.label}</h2></div><RiskBadge level={week.risk_level}/></div><p className="mt-5 text-xs font-bold uppercase text-slate-500">Brief drivers</p><ul className="mt-2 space-y-2">{week.drivers.map((driver) => <li className="flex items-start gap-2 text-sm leading-6 text-slate-600" key={driver}><Icon className="mt-1 h-4 w-4 shrink-0 text-blue-600" name="outlook"/>{driver}</li>)}</ul></article>)}</section><section className="mt-6 rounded-2xl border border-amber-200 bg-amber-50 p-6"><p className="font-bold text-amber-950">{state.forecast.disclaimer}</p><p className="mt-2 text-sm leading-6 text-amber-900">{state.forecast.explanation} Demo thresholds and drivers are not validated medical thresholds.</p></section></>}</div>;
}
export default OutlookPage;
